/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojnimy_JniClient */

#ifndef _Included_com_example_hellojnimy_JniClient
#define _Included_com_example_hellojnimy_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojnimy_JniClient
 * Method:    HelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojnimy_JniClient_HelloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
